
package kmv.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPWebServer", targetNamespace = "http://soap.kmv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPWebServer {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://soap.kmv/", className = "kmv.soap.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.AddStudentResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/addStudentRequest", output = "http://soap.kmv/SOAPWebServer/addStudentResponse")
    public void addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        StudentModel arg0);

    /**
     * 
     * @return
     *     returns java.util.List<kmv.soap.StudentModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStudents", targetNamespace = "http://soap.kmv/", className = "kmv.soap.GetAllStudents")
    @ResponseWrapper(localName = "getAllStudentsResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.GetAllStudentsResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/getAllStudentsRequest", output = "http://soap.kmv/SOAPWebServer/getAllStudentsResponse")
    public List<StudentModel> getAllStudents();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<kmv.soap.StudentModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findStudents", targetNamespace = "http://soap.kmv/", className = "kmv.soap.FindStudents")
    @ResponseWrapper(localName = "findStudentsResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.FindStudentsResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/findStudentsRequest", output = "http://soap.kmv/SOAPWebServer/findStudentsResponse")
    public List<StudentModel> findStudents(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchStudentTerms arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "findRemoveStudents", targetNamespace = "http://soap.kmv/", className = "kmv.soap.FindRemoveStudents")
    @ResponseWrapper(localName = "findRemoveStudentsResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.FindRemoveStudentsResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/findRemoveStudentsRequest", output = "http://soap.kmv/SOAPWebServer/findRemoveStudentsResponse")
    public void findRemoveStudents(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchStudentTerms arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentCount", targetNamespace = "http://soap.kmv/", className = "kmv.soap.GetStudentCount")
    @ResponseWrapper(localName = "getStudentCountResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.GetStudentCountResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/getStudentCountRequest", output = "http://soap.kmv/SOAPWebServer/getStudentCountResponse")
    public int getStudentCount();

    /**
     * 
     * @param arg0
     * @return
     *     returns kmv.soap.StudentModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentAtIndex", targetNamespace = "http://soap.kmv/", className = "kmv.soap.GetStudentAtIndex")
    @ResponseWrapper(localName = "getStudentAtIndexResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.GetStudentAtIndexResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/getStudentAtIndexRequest", output = "http://soap.kmv/SOAPWebServer/getStudentAtIndexResponse")
    public StudentModel getStudentAtIndex(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "saveChanges", targetNamespace = "http://soap.kmv/", className = "kmv.soap.SaveChanges")
    @ResponseWrapper(localName = "saveChangesResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.SaveChangesResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/saveChangesRequest", output = "http://soap.kmv/SOAPWebServer/saveChangesResponse")
    public void saveChanges();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeStudent", targetNamespace = "http://soap.kmv/", className = "kmv.soap.RemoveStudent")
    @ResponseWrapper(localName = "removeStudentResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.RemoveStudentResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/removeStudentRequest", output = "http://soap.kmv/SOAPWebServer/removeStudentResponse")
    public void removeStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        StudentModel arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStudent", targetNamespace = "http://soap.kmv/", className = "kmv.soap.UpdateStudent")
    @ResponseWrapper(localName = "updateStudentResponse", targetNamespace = "http://soap.kmv/", className = "kmv.soap.UpdateStudentResponse")
    @Action(input = "http://soap.kmv/SOAPWebServer/updateStudentRequest", output = "http://soap.kmv/SOAPWebServer/updateStudentResponse")
    public boolean updateStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        SearchStudentTerms arg0);

}
