
package kmv.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentWebServerService", targetNamespace = "http://soap.kmv/", wsdlLocation = "http://localhost:7103/hello?wsdl")
public class StudentWebServerService
    extends Service
{

    private final static URL STUDENTWEBSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTWEBSERVERSERVICE_EXCEPTION;
    private final static QName STUDENTWEBSERVERSERVICE_QNAME = new QName("http://soap.kmv/", "StudentWebServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7103/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTWEBSERVERSERVICE_WSDL_LOCATION = url;
        STUDENTWEBSERVERSERVICE_EXCEPTION = e;
    }

    public StudentWebServerService() {
        super(__getWsdlLocation(), STUDENTWEBSERVERSERVICE_QNAME);
    }

    public StudentWebServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTWEBSERVERSERVICE_QNAME, features);
    }

    public StudentWebServerService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTWEBSERVERSERVICE_QNAME);
    }

    public StudentWebServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTWEBSERVERSERVICE_QNAME, features);
    }

    public StudentWebServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWebServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPWebServer
     */
    @WebEndpoint(name = "StudentWebServerPort")
    public SOAPWebServer getStudentWebServerPort() {
        return super.getPort(new QName("http://soap.kmv/", "StudentWebServerPort"), SOAPWebServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPWebServer
     */
    @WebEndpoint(name = "StudentWebServerPort")
    public SOAPWebServer getStudentWebServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.kmv/", "StudentWebServerPort"), SOAPWebServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTWEBSERVERSERVICE_EXCEPTION!= null) {
            throw STUDENTWEBSERVERSERVICE_EXCEPTION;
        }
        return STUDENTWEBSERVERSERVICE_WSDL_LOCATION;
    }

}
